/**
 * Rewrites src/sidepanel/index.html into test/preview/index.html with the
 * Chrome API mock injected, so the real panel markup/CSS/JS can be exercised
 * in an ordinary tab. Generated file — never edit it by hand.
 *
 *   node tools/make-preview.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.join(root, 'src', 'sidepanel', 'index.html');
const outDir = path.join(root, 'test', 'preview');
const outFile = path.join(outDir, 'index.html');

let html = fs.readFileSync(source, 'utf8');

html = html
  .replace('<link rel="stylesheet" href="sidepanel.css">',
    '<link rel="stylesheet" href="../../src/sidepanel/sidepanel.css">\n  <link rel="stylesheet" href="preview.css">')
  .replace(/src="\.\.\/utils\//g, 'src="../../src/utils/')
  .replace('src="sidepanel.js"', 'src="../../src/sidepanel/sidepanel.js"')
  .replace('<script src="../../src/utils/constants.js"></script>',
    '<script src="mock-chrome.js"></script>\n  <script src="../../src/utils/constants.js"></script>')
  .replace('<title>Image Downloader</title>', '<title>Image Downloader — panel preview</title>')
  .replace('<body>', '<body>\n  <!-- GENERATED by tools/make-preview.mjs — edit src/sidepanel/index.html instead -->');

fs.mkdirSync(outDir, { recursive: true });
fs.writeFileSync(outFile, html);
console.log('wrote ' + path.relative(root, outFile));
